### ISSUE TITLE
Error during import of ontology with range restriction

### ISSUE THREAD

**Issue by palandlom** [jbarrasa/neosemantics#104]
It seems that Range restriction like:
```
Individual: highProductVolume
    Types: 
        ProductionVolume
 
    Facts:  
     hasVolumeValue  [>=100000]

DataProperty: hasVolumeValue

    Domain: 
        ProductionVolume
    
    Range: 
        xsd:integer
    
    SubPropertyOf: 
        owl:topDataProperty
```
... leads to error:
```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `semantics.importRDF`: Caused by: java.lang.NumberFormatException: For input string: "[>=100000]"
```

**Comment by jbarrasa** [comment]
Hi @palandlom can you post the RDF fragment that generates the error so I can try to reproduce?
Thanks!
JB.

**Comment by palandlom** [comment]
Here it is (https://drive.google.com/file/d/1ESlqsEKmMKotgHgMGWfI3w1aa5R23ieS/view?usp=sharing)

**Comment by jbarrasa** [comment]
Hi @palandlom , thanks for sharing. The problem seems quite simple. In your RDF fragment, there are some literal values being tagged as `xsd:integer` when in fact they are strings, so when the parser tries to treat them as integers it obviously fails. Here's a minimal case to reproduce it. I'll use N-Triples format for simplicity:

This triple is an example:

`<http://voc1#highProductVolume> <http://test-voc#hasVolumeValue> "[>=100000]"^^<http://www.w3.org/2001/XMLSchema#integer> .` 

if you try to run a preview in neosemantics... 

```
call semantics.previewRDFSnippet('
<http://voc1#highProductVolume> <http://test-voc#hasVolumeValue> "[>=100000]"^^<http://www.w3.org/2001/XMLSchema#integer> .
',"N-Triples")
```
...you'll get exactly the same error:

```Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `semantics.previewRDFSnippet`: Caused by: java.lang.NumberFormatException: For input string: "[>=100000]"```

I guess the reasonable thing to do would be to remove the `xsd:integer` annotation from the values that are not actual integers.

Hope this helps.

JB.

**Comment by palandlom** [comment]
Ahh... There is other problem appear - if I remove `xsd:integer` from triple
```
<http://voc1#highProductVolume> <http://test-voc#hasVolumeValue> [>=100000]"^^<http://www.w3.org/2001/XMLSchema#integer> .
```
OWL reasoner - Hermit says that ontology is inconsistent because there is anoter triple saying the datatype property `hasVolumeValue` has range `#integer` so I have to remove that range definition triple too) (i.e. Range now is empty)

PS: But now I understand why Hermit fails during inference. Thank for assistance)
