### ISSUE TITLE
RDFImportTest error 

### ISSUE THREAD

**Issue by corinabioinformatic** [jbarrasa/neosemantics#34]
Dear neosemantics team, (NOTE: I'm using Neo4J CE 3.2.3, and Neo4J Browser 3.0.5)
1) 
I'm trying to build the jar files running the [source code unziped ](https://github.com/jbarrasa/neosemantics/releases) by mean of mvn clean package but it retrieves this error:
![imagen](https://user-images.githubusercontent.com/14955321/32289458-af62a5ee-bf2e-11e7-84eb-01085cc0f9f5.png)

And I'm unable to get the jar files on this way.
 2)
In addition wWhen I copy paste the provided jar file into the plugin folder at Neo4J and run the server it does not find the semantic procedures (I created the config folder with the neo4j.config file following the instructions). Could

**Comment by jbarrasa** [comment]
Hi,
1) Would it be possible to have a look at the error report (surefire-report folder)? or you can maybe share what test is failing?

2) Some obvious questions: Have you restarted Neo4j after copying the jar to the plugins dir? (note the name `plugins` not `plugin`) Is there any error logged? Have you been able to use other stored proc libraries like apoc? I'm trying to figure out if the problem is exclusive of neosemantics.

Thanks!

JB.
