### ISSUE TITLE
namespaces {}?

### ISSUE THREAD

**Issue by pbh77** [jbarrasa/neosemantics#56]
I am trying to determine how to get more details about the cause of a failure to import an RDF file. 

I attempted to import the file available at https://ebiquity.umbc.edu/get/a/resource/361.rdf

The file successfully loads in Protege 5.20. When I used the procedure CALL semantics.importRDF("Cloud-Security-and-Compliance-Onotology-UMBC-361.rdf","RDF/XML", {shortenUrls: false, typesToLabels: true })

The result was termination status "OK, 0 triples loaded, namespaces { }, extrainfo "".  Started streaming 1 records after 22 ms and completed after 22 ms.

I installed by copying the file https://github.com/jbarrasa/neosemantics/releases/download/3.4.0.1/neosemantics-3.4.0.1.jar and following the instructions at https://github.com/jbarrasa/neosemantics.

The installation is on neo4j version 3.4.4, the community edition. I found no log information generated by the failed call to semantics.importRDF.

**Comment by jbarrasa** [comment]
Hi pbh77, thanks for trying out neosemantics and sorry for the late reply.
The problem is that the RDF file you're trying to load is actually not serialised as RDF/XML, it's Turtle (https://www.w3.org/TR/turtle/).

All you need to do is set the format param to the right value (`Turtle` in this case) just like this:
`semantics.importRDF("Cloud-Security-and-Compliance-Onotology-UMBC-361.rdf","Turtle", {shortenUrls: false, typesToLabels: true })` 

Let me know if this helps.

JB.
